# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\parai@foxmail.com\nt\gainos-tkernel\gainos_studio\ui_forms\comstack\canif\CanIf_Dlg.ui'
#
# Created: Thu Apr 04 20:33:07 2013
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CanIf_Dlg(object):
    def setupUi(self, CanIf_Dlg):
        CanIf_Dlg.setObjectName(_fromUtf8("CanIf_Dlg"))
        CanIf_Dlg.resize(965, 577)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        CanIf_Dlg.setFont(font)
        self.groupBox = QtGui.QGroupBox(CanIf_Dlg)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 941, 151))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 32, 250, 112))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.cbxDevErr = QtGui.QCheckBox(self.layoutWidget)
        self.cbxDevErr.setObjectName(_fromUtf8("cbxDevErr"))
        self.verticalLayout.addWidget(self.cbxDevErr)
        self.cbxVersionInfo = QtGui.QCheckBox(self.layoutWidget)
        self.cbxVersionInfo.setObjectName(_fromUtf8("cbxVersionInfo"))
        self.verticalLayout.addWidget(self.cbxVersionInfo)
        self.cbxDlcCheck = QtGui.QCheckBox(self.layoutWidget)
        self.cbxDlcCheck.setObjectName(_fromUtf8("cbxDlcCheck"))
        self.verticalLayout.addWidget(self.cbxDlcCheck)
        self.cbxRuntimePduCfg = QtGui.QCheckBox(self.layoutWidget)
        self.cbxRuntimePduCfg.setObjectName(_fromUtf8("cbxRuntimePduCfg"))
        self.verticalLayout.addWidget(self.cbxRuntimePduCfg)
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(310, 40, 551, 95))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_34 = QtGui.QLabel(self.layoutWidget1)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout.addWidget(self.label_34)
        self.leBusoffNf = QtGui.QLineEdit(self.layoutWidget1)
        self.leBusoffNf.setMinimumSize(QtCore.QSize(250, 0))
        self.leBusoffNf.setText(_fromUtf8(""))
        self.leBusoffNf.setObjectName(_fromUtf8("leBusoffNf"))
        self.horizontalLayout.addWidget(self.leBusoffNf)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_35 = QtGui.QLabel(self.layoutWidget1)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_24.addWidget(self.label_35)
        self.leErrorNf = QtGui.QLineEdit(self.layoutWidget1)
        self.leErrorNf.setText(_fromUtf8(""))
        self.leErrorNf.setObjectName(_fromUtf8("leErrorNf"))
        self.horizontalLayout_24.addWidget(self.leErrorNf)
        self.verticalLayout_10.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.label_36 = QtGui.QLabel(self.layoutWidget1)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_37.addWidget(self.label_36)
        self.cmbxSoftwareFilterType = QtGui.QComboBox(self.layoutWidget1)
        self.cmbxSoftwareFilterType.setMinimumSize(QtCore.QSize(250, 0))
        self.cmbxSoftwareFilterType.setObjectName(_fromUtf8("cmbxSoftwareFilterType"))
        self.cmbxSoftwareFilterType.addItem(_fromUtf8(""))
        self.cmbxSoftwareFilterType.addItem(_fromUtf8(""))
        self.cmbxSoftwareFilterType.addItem(_fromUtf8(""))
        self.cmbxSoftwareFilterType.addItem(_fromUtf8(""))
        self.cmbxSoftwareFilterType.addItem(_fromUtf8(""))
        self.horizontalLayout_37.addWidget(self.cmbxSoftwareFilterType)
        self.verticalLayout_10.addLayout(self.horizontalLayout_37)
        self.groupBox_2 = QtGui.QGroupBox(CanIf_Dlg)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 170, 941, 401))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.trCanIfCfg = QtGui.QTreeWidget(self.groupBox_2)
        self.trCanIfCfg.setGeometry(QtCore.QRect(20, 30, 256, 371))
        self.trCanIfCfg.setObjectName(_fromUtf8("trCanIfCfg"))
        item_0 = QtGui.QTreeWidgetItem(self.trCanIfCfg)
        self.tabCfg = QtGui.QTabWidget(self.groupBox_2)
        self.tabCfg.setGeometry(QtCore.QRect(430, 20, 491, 381))
        self.tabCfg.setObjectName(_fromUtf8("tabCfg"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.widget = QtGui.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(60, 71, 331, 27))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_36 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_36.setMargin(0)
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.label_33 = QtGui.QLabel(self.widget)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_36.addWidget(self.label_33)
        self.leChannelName = QtGui.QLineEdit(self.widget)
        self.leChannelName.setText(_fromUtf8(""))
        self.leChannelName.setObjectName(_fromUtf8("leChannelName"))
        self.horizontalLayout_36.addWidget(self.leChannelName)
        self.tabCfg.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.layoutWidget_3 = QtGui.QWidget(self.tab_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 20, 362, 229))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.label_32 = QtGui.QLabel(self.layoutWidget_3)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_35.addWidget(self.label_32)
        self.leHthName = QtGui.QLineEdit(self.layoutWidget_3)
        self.leHthName.setText(_fromUtf8(""))
        self.leHthName.setObjectName(_fromUtf8("leHthName"))
        self.horizontalLayout_35.addWidget(self.leHthName)
        self.verticalLayout_8.addLayout(self.horizontalLayout_35)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_25 = QtGui.QLabel(self.layoutWidget_3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_28.addWidget(self.label_25)
        self.cmbxHohType = QtGui.QComboBox(self.layoutWidget_3)
        self.cmbxHohType.setMinimumSize(QtCore.QSize(250, 0))
        self.cmbxHohType.setObjectName(_fromUtf8("cmbxHohType"))
        self.cmbxHohType.addItem(_fromUtf8(""))
        self.cmbxHohType.addItem(_fromUtf8(""))
        self.horizontalLayout_28.addWidget(self.cmbxHohType)
        self.verticalLayout_5.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_26 = QtGui.QLabel(self.layoutWidget_3)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_29.addWidget(self.label_26)
        self.cmbxIdType = QtGui.QComboBox(self.layoutWidget_3)
        self.cmbxIdType.setObjectName(_fromUtf8("cmbxIdType"))
        self.cmbxIdType.addItem(_fromUtf8(""))
        self.cmbxIdType.addItem(_fromUtf8(""))
        self.horizontalLayout_29.addWidget(self.cmbxIdType)
        self.verticalLayout_5.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.label_27 = QtGui.QLabel(self.layoutWidget_3)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_30.addWidget(self.label_27)
        self.spbxIdValue = QtGui.QSpinBox(self.layoutWidget_3)
        self.spbxIdValue.setObjectName(_fromUtf8("spbxIdValue"))
        self.horizontalLayout_30.addWidget(self.spbxIdValue)
        self.verticalLayout_5.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_28 = QtGui.QLabel(self.layoutWidget_3)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_31.addWidget(self.label_28)
        self.cmbxObjType = QtGui.QComboBox(self.layoutWidget_3)
        self.cmbxObjType.setObjectName(_fromUtf8("cmbxObjType"))
        self.cmbxObjType.addItem(_fromUtf8(""))
        self.cmbxObjType.addItem(_fromUtf8(""))
        self.horizontalLayout_31.addWidget(self.cmbxObjType)
        self.verticalLayout_5.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_29 = QtGui.QLabel(self.layoutWidget_3)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_32.addWidget(self.label_29)
        self.cmbxFilterMask = QtGui.QComboBox(self.layoutWidget_3)
        self.cmbxFilterMask.setMinimumSize(QtCore.QSize(231, 0))
        self.cmbxFilterMask.setObjectName(_fromUtf8("cmbxFilterMask"))
        self.horizontalLayout_32.addWidget(self.cmbxFilterMask)
        self.verticalLayout_5.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.label_30 = QtGui.QLabel(self.layoutWidget_3)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_33.addWidget(self.label_30)
        self.leMbMask = QtGui.QLineEdit(self.layoutWidget_3)
        self.leMbMask.setText(_fromUtf8(""))
        self.leMbMask.setObjectName(_fromUtf8("leMbMask"))
        self.horizontalLayout_33.addWidget(self.leMbMask)
        self.verticalLayout_5.addLayout(self.horizontalLayout_33)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.tabCfg.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.layoutWidget_6 = QtGui.QWidget(self.tab_4)
        self.layoutWidget_6.setGeometry(QtCore.QRect(20, 20, 362, 229))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.label_37 = QtGui.QLabel(self.layoutWidget_6)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_38.addWidget(self.label_37)
        self.leHrhName = QtGui.QLineEdit(self.layoutWidget_6)
        self.leHrhName.setText(_fromUtf8(""))
        self.leHrhName.setObjectName(_fromUtf8("leHrhName"))
        self.horizontalLayout_38.addWidget(self.leHrhName)
        self.verticalLayout_9.addLayout(self.horizontalLayout_38)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.label_38 = QtGui.QLabel(self.layoutWidget_6)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_39.addWidget(self.label_38)
        self.cmbxHohType_2 = QtGui.QComboBox(self.layoutWidget_6)
        self.cmbxHohType_2.setMinimumSize(QtCore.QSize(250, 0))
        self.cmbxHohType_2.setObjectName(_fromUtf8("cmbxHohType_2"))
        self.cmbxHohType_2.addItem(_fromUtf8(""))
        self.cmbxHohType_2.addItem(_fromUtf8(""))
        self.horizontalLayout_39.addWidget(self.cmbxHohType_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.label_39 = QtGui.QLabel(self.layoutWidget_6)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_40.addWidget(self.label_39)
        self.cmbxIdType_2 = QtGui.QComboBox(self.layoutWidget_6)
        self.cmbxIdType_2.setObjectName(_fromUtf8("cmbxIdType_2"))
        self.cmbxIdType_2.addItem(_fromUtf8(""))
        self.cmbxIdType_2.addItem(_fromUtf8(""))
        self.horizontalLayout_40.addWidget(self.cmbxIdType_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.label_40 = QtGui.QLabel(self.layoutWidget_6)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_41.addWidget(self.label_40)
        self.spbxIdValue_2 = QtGui.QSpinBox(self.layoutWidget_6)
        self.spbxIdValue_2.setObjectName(_fromUtf8("spbxIdValue_2"))
        self.horizontalLayout_41.addWidget(self.spbxIdValue_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_42 = QtGui.QHBoxLayout()
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.label_41 = QtGui.QLabel(self.layoutWidget_6)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.horizontalLayout_42.addWidget(self.label_41)
        self.cmbxObjType_2 = QtGui.QComboBox(self.layoutWidget_6)
        self.cmbxObjType_2.setObjectName(_fromUtf8("cmbxObjType_2"))
        self.cmbxObjType_2.addItem(_fromUtf8(""))
        self.cmbxObjType_2.addItem(_fromUtf8(""))
        self.horizontalLayout_42.addWidget(self.cmbxObjType_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_43 = QtGui.QHBoxLayout()
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        self.label_42 = QtGui.QLabel(self.layoutWidget_6)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.horizontalLayout_43.addWidget(self.label_42)
        self.cmbxFilterMask_2 = QtGui.QComboBox(self.layoutWidget_6)
        self.cmbxFilterMask_2.setMinimumSize(QtCore.QSize(231, 0))
        self.cmbxFilterMask_2.setObjectName(_fromUtf8("cmbxFilterMask_2"))
        self.horizontalLayout_43.addWidget(self.cmbxFilterMask_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtGui.QHBoxLayout()
        self.horizontalLayout_44.setObjectName(_fromUtf8("horizontalLayout_44"))
        self.label_43 = QtGui.QLabel(self.layoutWidget_6)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.horizontalLayout_44.addWidget(self.label_43)
        self.leMbMask_2 = QtGui.QLineEdit(self.layoutWidget_6)
        self.leMbMask_2.setText(_fromUtf8(""))
        self.leMbMask_2.setObjectName(_fromUtf8("leMbMask_2"))
        self.horizontalLayout_44.addWidget(self.leMbMask_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_44)
        self.verticalLayout_9.addLayout(self.verticalLayout_6)
        self.tabCfg.addTab(self.tab_4, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.layoutWidget_4 = QtGui.QWidget(self.tab_3)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 110, 461, 136))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.layoutWidget_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.leIdar0 = QtGui.QLineEdit(self.layoutWidget_4)
        self.leIdar0.setText(_fromUtf8(""))
        self.leIdar0.setObjectName(_fromUtf8("leIdar0"))
        self.horizontalLayout_3.addWidget(self.leIdar0)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.layoutWidget_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.leIdar1 = QtGui.QLineEdit(self.layoutWidget_4)
        self.leIdar1.setText(_fromUtf8(""))
        self.leIdar1.setObjectName(_fromUtf8("leIdar1"))
        self.horizontalLayout_4.addWidget(self.leIdar1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.layoutWidget_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.leIdar2 = QtGui.QLineEdit(self.layoutWidget_4)
        self.leIdar2.setText(_fromUtf8(""))
        self.leIdar2.setObjectName(_fromUtf8("leIdar2"))
        self.horizontalLayout_5.addWidget(self.leIdar2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(self.layoutWidget_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.leIdar3 = QtGui.QLineEdit(self.layoutWidget_4)
        self.leIdar3.setText(_fromUtf8(""))
        self.leIdar3.setObjectName(_fromUtf8("leIdar3"))
        self.horizontalLayout_6.addWidget(self.leIdar3)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_8 = QtGui.QLabel(self.layoutWidget_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_9.addWidget(self.label_8)
        self.leIdmr0 = QtGui.QLineEdit(self.layoutWidget_4)
        self.leIdmr0.setText(_fromUtf8(""))
        self.leIdmr0.setObjectName(_fromUtf8("leIdmr0"))
        self.horizontalLayout_9.addWidget(self.leIdmr0)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_9 = QtGui.QLabel(self.layoutWidget_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_10.addWidget(self.label_9)
        self.leIdmr1 = QtGui.QLineEdit(self.layoutWidget_4)
        self.leIdmr1.setText(_fromUtf8(""))
        self.leIdmr1.setObjectName(_fromUtf8("leIdmr1"))
        self.horizontalLayout_10.addWidget(self.leIdmr1)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_10 = QtGui.QLabel(self.layoutWidget_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_11.addWidget(self.label_10)
        self.leIdmr2 = QtGui.QLineEdit(self.layoutWidget_4)
        self.leIdmr2.setText(_fromUtf8(""))
        self.leIdmr2.setObjectName(_fromUtf8("leIdmr2"))
        self.horizontalLayout_11.addWidget(self.leIdmr2)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_11 = QtGui.QLabel(self.layoutWidget_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_12.addWidget(self.label_11)
        self.leIdmr3 = QtGui.QLineEdit(self.layoutWidget_4)
        self.leIdmr3.setText(_fromUtf8(""))
        self.leIdmr3.setObjectName(_fromUtf8("leIdmr3"))
        self.horizontalLayout_12.addWidget(self.leIdmr3)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_16 = QtGui.QLabel(self.layoutWidget_4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_19.addWidget(self.label_16)
        self.leIdar4 = QtGui.QLineEdit(self.layoutWidget_4)
        self.leIdar4.setText(_fromUtf8(""))
        self.leIdar4.setObjectName(_fromUtf8("leIdar4"))
        self.horizontalLayout_19.addWidget(self.leIdar4)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_17 = QtGui.QLabel(self.layoutWidget_4)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_20.addWidget(self.label_17)
        self.leIdar5 = QtGui.QLineEdit(self.layoutWidget_4)
        self.leIdar5.setText(_fromUtf8(""))
        self.leIdar5.setObjectName(_fromUtf8("leIdar5"))
        self.horizontalLayout_20.addWidget(self.leIdar5)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_18 = QtGui.QLabel(self.layoutWidget_4)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_21.addWidget(self.label_18)
        self.leIdar6 = QtGui.QLineEdit(self.layoutWidget_4)
        self.leIdar6.setText(_fromUtf8(""))
        self.leIdar6.setObjectName(_fromUtf8("leIdar6"))
        self.horizontalLayout_21.addWidget(self.leIdar6)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_19 = QtGui.QLabel(self.layoutWidget_4)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_22.addWidget(self.label_19)
        self.leIdar7 = QtGui.QLineEdit(self.layoutWidget_4)
        self.leIdar7.setText(_fromUtf8(""))
        self.leIdar7.setObjectName(_fromUtf8("leIdar7"))
        self.horizontalLayout_22.addWidget(self.leIdar7)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_22)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_12 = QtGui.QLabel(self.layoutWidget_4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_14.addWidget(self.label_12)
        self.leIdmr4 = QtGui.QLineEdit(self.layoutWidget_4)
        self.leIdmr4.setText(_fromUtf8(""))
        self.leIdmr4.setObjectName(_fromUtf8("leIdmr4"))
        self.horizontalLayout_14.addWidget(self.leIdmr4)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_13 = QtGui.QLabel(self.layoutWidget_4)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_15.addWidget(self.label_13)
        self.leIdmr5 = QtGui.QLineEdit(self.layoutWidget_4)
        self.leIdmr5.setText(_fromUtf8(""))
        self.leIdmr5.setObjectName(_fromUtf8("leIdmr5"))
        self.horizontalLayout_15.addWidget(self.leIdmr5)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_14 = QtGui.QLabel(self.layoutWidget_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_16.addWidget(self.label_14)
        self.leIdmr6 = QtGui.QLineEdit(self.layoutWidget_4)
        self.leIdmr6.setText(_fromUtf8(""))
        self.leIdmr6.setObjectName(_fromUtf8("leIdmr6"))
        self.horizontalLayout_16.addWidget(self.leIdmr6)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_15 = QtGui.QLabel(self.layoutWidget_4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_17.addWidget(self.label_15)
        self.leIdmr7 = QtGui.QLineEdit(self.layoutWidget_4)
        self.leIdmr7.setText(_fromUtf8(""))
        self.leIdmr7.setObjectName(_fromUtf8("leIdmr7"))
        self.horizontalLayout_17.addWidget(self.leIdmr7)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_17)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.layoutWidget_5 = QtGui.QWidget(self.tab_3)
        self.layoutWidget_5.setGeometry(QtCore.QRect(50, 30, 279, 62))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.label_31 = QtGui.QLabel(self.layoutWidget_5)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_34.addWidget(self.label_31)
        self.leFmName = QtGui.QLineEdit(self.layoutWidget_5)
        self.leFmName.setText(_fromUtf8(""))
        self.leFmName.setObjectName(_fromUtf8("leFmName"))
        self.horizontalLayout_34.addWidget(self.leFmName)
        self.verticalLayout_7.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.layoutWidget_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.cmbxIdam = QtGui.QComboBox(self.layoutWidget_5)
        self.cmbxIdam.setObjectName(_fromUtf8("cmbxIdam"))
        self.cmbxIdam.addItem(_fromUtf8(""))
        self.cmbxIdam.addItem(_fromUtf8(""))
        self.cmbxIdam.addItem(_fromUtf8(""))
        self.cmbxIdam.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cmbxIdam)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.tabCfg.addTab(self.tab_3, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tabCfg.addTab(self.tab_5, _fromUtf8(""))
        self.widget1 = QtGui.QWidget(self.groupBox_2)
        self.widget1.setGeometry(QtCore.QRect(290, 51, 131, 95))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.btnAdd = QtGui.QPushButton(self.widget1)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.verticalLayout_2.addWidget(self.btnAdd)
        self.btnAdd2 = QtGui.QPushButton(self.widget1)
        self.btnAdd2.setObjectName(_fromUtf8("btnAdd2"))
        self.verticalLayout_2.addWidget(self.btnAdd2)
        self.btnDel = QtGui.QPushButton(self.widget1)
        self.btnDel.setObjectName(_fromUtf8("btnDel"))
        self.verticalLayout_2.addWidget(self.btnDel)

        self.retranslateUi(CanIf_Dlg)
        self.tabCfg.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(CanIf_Dlg)

    def retranslateUi(self, CanIf_Dlg):
        CanIf_Dlg.setWindowTitle(QtGui.QApplication.translate("CanIf_Dlg", "Can Interface", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("CanIf_Dlg", "CanIf General", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxDevErr.setText(QtGui.QApplication.translate("CanIf_Dlg", "DevErrorDetection", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxVersionInfo.setText(QtGui.QApplication.translate("CanIf_Dlg", "VersionInfoApi", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxDlcCheck.setText(QtGui.QApplication.translate("CanIf_Dlg", "DLC Check Support", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxRuntimePduCfg.setText(QtGui.QApplication.translate("CanIf_Dlg", "Runtime Pdu Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("CanIf_Dlg", "Busoff Notification Function:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("CanIf_Dlg", "Error Notification Function:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("CanIf_Dlg", "Software Filter Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSoftwareFilterType.setItemText(0, QtGui.QApplication.translate("CanIf_Dlg", "CANIF_SOFTFILTER_TYPE_MASK", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSoftwareFilterType.setItemText(1, QtGui.QApplication.translate("CanIf_Dlg", "CANIF_SOFTFILTER_TYPE_BINARY", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSoftwareFilterType.setItemText(2, QtGui.QApplication.translate("CanIf_Dlg", "CANIF_SOFTFILTER_TYPE_INDEX", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSoftwareFilterType.setItemText(3, QtGui.QApplication.translate("CanIf_Dlg", "CANIF_SOFTFILTER_TYPE_LINEAR", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSoftwareFilterType.setItemText(4, QtGui.QApplication.translate("CanIf_Dlg", "CANIF_SOFTFILTER_TYPE_TABLE", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("CanIf_Dlg", "CanIf Entities", None, QtGui.QApplication.UnicodeUTF8))
        self.trCanIfCfg.headerItem().setText(0, QtGui.QApplication.translate("CanIf_Dlg", "Can", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.trCanIfCfg.isSortingEnabled()
        self.trCanIfCfg.setSortingEnabled(False)
        self.trCanIfCfg.topLevelItem(0).setText(0, QtGui.QApplication.translate("CanIf_Dlg", "Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.trCanIfCfg.setSortingEnabled(__sortingEnabled)
        self.label_33.setText(QtGui.QApplication.translate("CanIf_Dlg", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCfg.setTabText(self.tabCfg.indexOf(self.tab), QtGui.QApplication.translate("CanIf_Dlg", "Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("CanIf_Dlg", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("CanIf_Dlg", "Hoh Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxHohType.setItemText(0, QtGui.QApplication.translate("CanIf_Dlg", "CAN_ARC_HANDLE_TYPE_BASIC", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxHohType.setItemText(1, QtGui.QApplication.translate("CanIf_Dlg", "CAN_ARC_HANDLE_TYPE_FULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("CanIf_Dlg", "Id Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxIdType.setItemText(0, QtGui.QApplication.translate("CanIf_Dlg", "CAN_ID_TYPE_EXTENDED", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxIdType.setItemText(1, QtGui.QApplication.translate("CanIf_Dlg", "CAN_ID_TYPE_STANDARD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("CanIf_Dlg", "Id Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("CanIf_Dlg", "Object Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxObjType.setItemText(0, QtGui.QApplication.translate("CanIf_Dlg", "CAN_OBJECT_TYPE_RECEIVE", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxObjType.setItemText(1, QtGui.QApplication.translate("CanIf_Dlg", "CAN_OBJECT_TYPE_TRANSMIT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("CanIf_Dlg", "Filter Mask:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("CanIf_Dlg", "MbMask:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCfg.setTabText(self.tabCfg.indexOf(self.tab_2), QtGui.QApplication.translate("CanIf_Dlg", "Hth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("CanIf_Dlg", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("CanIf_Dlg", "Hoh Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxHohType_2.setItemText(0, QtGui.QApplication.translate("CanIf_Dlg", "CAN_ARC_HANDLE_TYPE_BASIC", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxHohType_2.setItemText(1, QtGui.QApplication.translate("CanIf_Dlg", "CAN_ARC_HANDLE_TYPE_FULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("CanIf_Dlg", "Id Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxIdType_2.setItemText(0, QtGui.QApplication.translate("CanIf_Dlg", "CAN_ID_TYPE_EXTENDED", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxIdType_2.setItemText(1, QtGui.QApplication.translate("CanIf_Dlg", "CAN_ID_TYPE_STANDARD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("CanIf_Dlg", "Id Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("CanIf_Dlg", "Object Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxObjType_2.setItemText(0, QtGui.QApplication.translate("CanIf_Dlg", "CAN_OBJECT_TYPE_RECEIVE", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxObjType_2.setItemText(1, QtGui.QApplication.translate("CanIf_Dlg", "CAN_OBJECT_TYPE_TRANSMIT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("CanIf_Dlg", "Filter Mask:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("CanIf_Dlg", "MbMask:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCfg.setTabText(self.tabCfg.indexOf(self.tab_4), QtGui.QApplication.translate("CanIf_Dlg", "Hrh", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CanIf_Dlg", "idar0:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("CanIf_Dlg", "idar1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("CanIf_Dlg", "idar2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("CanIf_Dlg", "idar3:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("CanIf_Dlg", "idmr0:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("CanIf_Dlg", "idmr1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("CanIf_Dlg", "idmr2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("CanIf_Dlg", "idmr3:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("CanIf_Dlg", "idar4:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("CanIf_Dlg", "idar5:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("CanIf_Dlg", "idar6:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("CanIf_Dlg", "idar7:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("CanIf_Dlg", "idmr4:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("CanIf_Dlg", "idmr5:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("CanIf_Dlg", "idmr6:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("CanIf_Dlg", "idmr7:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("CanIf_Dlg", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CanIf_Dlg", "IDAM:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxIdam.setItemText(0, QtGui.QApplication.translate("CanIf_Dlg", "CAN_IDAM_2_32BIT", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxIdam.setItemText(1, QtGui.QApplication.translate("CanIf_Dlg", "CAN_IDAM_4_16BIT", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxIdam.setItemText(2, QtGui.QApplication.translate("CanIf_Dlg", "CAN_IDAM_8_8BIT", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxIdam.setItemText(3, QtGui.QApplication.translate("CanIf_Dlg", "CAN_IDAM_FILTER_CLOSED", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCfg.setTabText(self.tabCfg.indexOf(self.tab_3), QtGui.QApplication.translate("CanIf_Dlg", "Tx Pdu", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCfg.setTabText(self.tabCfg.indexOf(self.tab_5), QtGui.QApplication.translate("CanIf_Dlg", "Rx Pdu", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setText(QtGui.QApplication.translate("CanIf_Dlg", "Add Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd2.setText(QtGui.QApplication.translate("CanIf_Dlg", "Add Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDel.setText(QtGui.QApplication.translate("CanIf_Dlg", "Del", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    CanIf_Dlg = QtGui.QDialog()
    ui = Ui_CanIf_Dlg()
    ui.setupUi(CanIf_Dlg)
    CanIf_Dlg.show()
    sys.exit(app.exec_())

