/*
* Configuration of module: PduR (PduR_PbCfg.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    HCS12
*
* Module vendor:           ArcCore
* Generator version:       3.1.10
*
* Generated by Arctic Studio (http://arccore.com) 
*/


#include "PduR.h"

const PduR_PBConfigType PduR_Config = {
	/* .PduRConfigurationId = */ 0,
	/* .NRoutingPaths = */ 0
//	/* .RoutingPaths = */ NULL,
//	/* .TpBuffers = */ NULL,
//	/* .TpRouteBuffers = */ NULL,
};
