/*
 * Configuration of module: PduR (PduR_PbCfg.c)
 *
 * Created by:              
 * Copyright:               
 *
 * Configured for (MCU):    HCS12
 *
 * Module vendor:           ArcCore
 * Generator version:       3.1.10
 *
 * Generated by Arctic Studio (http://arccore.com) 
 */


#include "PduR.h"


#if PDUR_CANIF_SUPPORT == STD_ON
#include "CanIf.h"
#endif
#if PDUR_CANTP_SUPPORT == STD_ON
#include "CanTp.h"
#endif
#if PDUR_LINIF_SUPPORT == STD_ON
#include "LinIf.h"
#endif
#if PDUR_COM_SUPPORT == STD_ON
#include "Com.h"
#endif
#if PDUR_DCM_SUPPORT == STD_ON
#include "Dcm.h"
#endif
#if PDUR_J1939TP_SUPPORT == STD_ON
#include "J1939Tp.h"
#endif
 		
uint8 ArcPduRTpBufferPduRTpBuffer1[64];
const PduInfoType ArcPduRTpBufferStructPduRTpBuffer1 = {
	/* .SduDataPtr = */ ArcPduRTpBufferPduRTpBuffer1,
	/* .SduLength = */ 64
};
 		
uint8 ArcPduRTpBufferPduRTpBuffer2[128];
const PduInfoType ArcPduRTpBufferStructPduRTpBuffer2 = {
	/* .SduDataPtr = */ ArcPduRTpBufferPduRTpBuffer2,
	/* .SduLength = */ 128
};



const PduRTpBufferInfo_type PduRTpBuffers[] = {
	{
		/* .pduInfoPtr = */ &ArcPduRTpBufferStructPduRTpBuffer1,
		/* .status = */ PDUR_BUFFER_FREE,
		/* .bufferSize = */ 64,
	},
	{
		/* .pduInfoPtr = */ &ArcPduRTpBufferStructPduRTpBuffer2,
		/* .status =  */PDUR_BUFFER_FREE,
		/* .bufferSize = */ 128,
	},
};

const PduRTpBufferInfo_type *PduRTpRouteBufferPtrs[] = {
	NULL,
	NULL,
	NULL,
	NULL,
    NULL
};


		
const PduRDestPdu_type PduRDestination_PDU_0_PduRDestination = {
    /* .DataProvision = */ PDUR_NO_PROVISION,
    /* .DestPduId = */ 0,//CANTP_PDU_ID_PDU_4,
    /* .TxBufferRef = */ NULL,
    /* .DestModule = */ ARC_PDUR_CANTP,
}; 		
const PduRDestPdu_type PduRDestination_PDU_1_PduRDestination = {
    /* .DataProvision = */ PDUR_NO_PROVISION,
    /* .DestPduId = */ 1,//CANTP_PDU_ID_PDU_5,
    /* .TxBufferRef = */ NULL ,
    /* .DestModule = */ ARC_PDUR_CANTP, 
}; 		
const PduRDestPdu_type PduRDestination_PDU_2_PduRDestination = {
    /* .DataProvision = */ PDUR_NO_PROVISION,
    /* .DestPduId = */ 2,//CANTP_PDU_ID_PDU_6,
    /* .TxBufferRef = */ NULL,
    /* .DestModule = */ ARC_PDUR_CANTP,
}; 		
const PduRDestPdu_type PduRDestination_PDU_3_PduRDestination = {
    /* .DataProvision = */ PDUR_NO_PROVISION,
    /* .DestPduId = */ 3,//CANTP_PDU_ID_PDU_7,
    /* .TxBufferRef = */ NULL,
    /* .DestModule = */ ARC_PDUR_CANTP,
}; 

const PduRDestPdu_type * const PduRDestinations_PDU_0[] = {		
	&PduRDestination_PDU_0_PduRDestination,
	NULL
};
const PduRDestPdu_type * const PduRDestinations_PDU_1[] = {		
	&PduRDestination_PDU_1_PduRDestination,
	NULL
};
const PduRDestPdu_type * const PduRDestinations_PDU_2[] = {		
	&PduRDestination_PDU_2_PduRDestination,
	NULL
};
const PduRDestPdu_type * const PduRDestinations_PDU_3[] = {		
	&PduRDestination_PDU_3_PduRDestination,
	NULL
};


const PduRRoutingPath_type PduRRoutingPath_PDU_0 = { 
	/* .SduLength = */ 0,
    /* .TpChunkSize = */0xDEAD,
    /* .PduRDefaultValue = */{0xDB,NULL},
    /* .SrcPduId = */ 0,//CANTP_PDU_ID_PDU_0,
	/* .SrcModule =  */ARC_PDUR_CANTP,	
	/* .PduRDestPdus = */ PduRDestinations_PDU_0
};	
const PduRRoutingPath_type PduRRoutingPath_PDU_1 = { 
	/* .SduLength = */ 0,
    /* .TpChunkSize = */0xDEAD,
    /* .PduRDefaultValue = */{0xDB,NULL},
    /* .SrcPduId = */ 1,//CANTP_PDU_ID_PDU_1,
	/* .SrcModule =  */ARC_PDUR_CANTP,	
	/* .PduRDestPdus = */ PduRDestinations_PDU_1
};	
const PduRRoutingPath_type PduRRoutingPath_PDU_2 = { 
	/* .SduLength = */ 0,
    /* .TpChunkSize = */0xDEAD,
    /* .PduRDefaultValue = */{0xDB,NULL},
    /* .SrcPduId = */ 2,//CANTP_PDU_ID_PDU_2,
	/* .SrcModule =  */ARC_PDUR_CANTP,	
	/* .PduRDestPdus = */ PduRDestinations_PDU_2
};	
const PduRRoutingPath_type PduRRoutingPath_PDU_3 = { 
	/* .SduLength = */ 0,
    /* .TpChunkSize = */0xDEAD,
    /* .PduRDefaultValue = */{0xDB,NULL},
    /* .SrcPduId = */ 3,//CANTP_PDU_ID_PDU_3,
	/* .SrcModule =  */ARC_PDUR_CANTP,	
	/* .PduRDestPdus = */ PduRDestinations_PDU_3
};	


const PduRRoutingPath_type * const PduRRoutingPaths[] = { 
	&PduRRoutingPath_PDU_0,
	&PduRRoutingPath_PDU_1,
	&PduRRoutingPath_PDU_2,
	&PduRRoutingPath_PDU_3,
	NULL
};


const PduR_PBConfigType PduR_Config = {
	/* .PduRConfigurationId = */ 0,
	/* .NRoutingPaths = */ 4,
	/* .RoutingPaths = */ PduRRoutingPaths,
	/* .TpBuffers = */ PduRTpBuffers,
	/* .TpRouteBuffers = */ PduRTpRouteBufferPtrs
};
